# Generated by manual intervention
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_planchoice_cost_alter_subscription_cost'),
    ]

    operations = [
        # Renomear a coluna 'plan' para 'plan_code' se necessário
        migrations.RenameField(
            model_name='planchoice',
            old_name='plan',
            new_name='plan_code',
        ),

        # Adicionar os campos ausentes
        migrations.AddField(
            model_name='planchoice',
            name='description1',
            field=models.CharField(default='Descrição do plano', max_length=300, verbose_name='Plan description 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planchoice',
            name='description2',
            field=models.CharField(default='Detalhes do plano', max_length=300, verbose_name='Plan description 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planchoice',
            name='external_plan_id',
            field=models.CharField(default='P-0000000000000000000000000', max_length=255, unique=True, verbose_name='External plan ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planchoice',
            name='external_api_url',
            field=models.CharField(default='https://www.paypal.com/sdk/js?client-id=YOUR_CLIENT_ID&vault=true&intent=subscription', max_length=2000, verbose_name='External API URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planchoice',
            name='external_style_json',
            field=models.CharField(default='{"shape":"pill","color":"gold","layout":"vertical","label":"subscribe"}', max_length=2000, verbose_name='External style JSON'),
            preserve_default=False,
        ),
        # Renomear a coluna 'price' para 'cost' se necessário
        migrations.RenameField(
            model_name='planchoice',
            old_name='price',
            new_name='cost',
        ),
    ] 